### ISSUE TITLE
BICO buy OK, but no SELL

### ISSUE THREAD

**Issue by dapytt** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#112]
2021-12-09 01:56:46,842 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:56:47,976 INFO: No coins announced, or coin has already been bought/sold. Checking more frequently in case TP and SL need updating
2021-12-09 01:56:50,112 INFO: Kucoin announcements enabled, look for new Kucoin coins...
2021-12-09 01:56:50,211 INFO: New coin detected: BICO
uppers='BICO'
2021-12-09 01:56:50,211 INFO: New listing detected
2021-12-09 01:56:50,211 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:56:50,979 INFO: New announcement detected: BICO
2021-12-09 01:56:52,062 INFO: LATEST TRADE: BICO_USDT | id=2364908413 | create_time=09-12-21 01:56:45.026000 | side=buy | amount=26.719 | price=7.11345
2021-12-09 01:56:52,062 INFO: starting buy place_order with : announcement_coin='BICO' | globals.pairing='USDT' | volume=100 | amount=14.05787627663089 x price='7.11345' | side = buy | status='test_partial_fill_order'
2021-12-09 01:56:52,860 INFO: PLACE ORDER: buy | 101857500343 | spot | limit | BICO_USDT | cancelled | amount=14.057 | price=7.11345 | left=14.057 | filled_total=0 | fill_price=0 | fee=0 BICO
2021-12-09 01:56:52,860 INFO: Order created on BICO at a price of 7.11345 each.  order_status='cancelled'
2021-12-09 01:56:53,485 INFO: Kucoin announcements enabled, look for new Kucoin coins...
2021-12-09 01:56:53,587 INFO: Clearing order with a status of cancelled.  Waiting for 'closed' status
uppers=None
2021-12-09 01:56:53,594 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:56:56,591 INFO: New announcement detected: BICO
2021-12-09 01:56:56,868 INFO: Kucoin announcements enabled, look for new Kucoin coins...
uppers=None
2021-12-09 01:56:56,964 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:56:57,379 INFO: LATEST TRADE: BICO_USDT | id=2364909562 | create_time=09-12-21 01:56:55.291000 | side=sell | amount=56.152 | price=7.18422
2021-12-09 01:56:57,379 INFO: starting buy place_order with : announcement_coin='BICO' | globals.pairing='USDT' | volume=100 | amount=13.919395564167022 x price='7.18422' | side = buy | status='test_partial_fill_order'
2021-12-09 01:56:58,159 INFO: PLACE ORDER: buy | 101857518346 | spot | limit | BICO_USDT | closed | amount=13.919 | price=7.18422 | left=0 | filled_total=99.61508163 | fill_price=99.61508163 | fee=0.027838 BICO
2021-12-09 01:56:58,159 INFO: Order created on BICO at a price of 7.18422 each.  order_status='closed'
2021-12-09 01:56:58,871 INFO: Order on BICO closed
2021-12-09 01:56:58,871 INFO: get_last_price existing coin: LINA
2021-12-09 01:57:00,237 INFO: Kucoin announcements enabled, look for new Kucoin coins...
uppers=None
2021-12-09 01:57:00,331 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:57:03,600 INFO: Kucoin announcements enabled, look for new Kucoin coins...
uppers=None
2021-12-09 01:57:03,683 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:57:06,955 INFO: Kucoin announcements enabled, look for new Kucoin coins...
uppers=None
2021-12-09 01:57:07,052 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:57:10,329 INFO: Kucoin announcements enabled, look for new Kucoin coins...
uppers=None
2021-12-09 01:57:10,417 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:57:13,684 INFO: Kucoin announcements enabled, look for new Kucoin coins...
uppers=None
2021-12-09 01:57:13,768 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:57:17,043 INFO: Kucoin announcements enabled, look for new Kucoin coins...
uppers=None
2021-12-09 01:57:17,135 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:57:20,409 INFO: Kucoin announcements enabled, look for new Kucoin coins...
uppers=None
2021-12-09 01:57:20,513 INFO: Checking for coin announcements every 3 seconds (in a separate thread)
2021-12-09 01:57:21,440 INFO: LATEST TRADE: LINA_USDT | id=2364913015 | create_time=09-12-21 01:57:18.703000 | side=sell | amount=149.354 | price=0.04291
2021-12-09 01:57:21,441 INFO: Finished get_last_price
2021-12-09 01:57:21,441 INFO: symbol='LINA'-last_price='0.04291'        [STOP: $0.03984 or -1.87%]      [TOP: $0.04233 or 4.26%]        [BUY: $0.04060 (+/-): 5.69%]
2021-12-09 01:57:21,442 INFO: updated tp: 6.535% / $0.043
2021-12-09 01:57:21,442 INFO: updated sl: 5.267% / $0.043
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 255, in sell
    logger.Info(f"Order is initialized but not ready. Continuing. | Status={st}")
AttributeError: 'Logger' object has no attribute 'Info'
2021-12-09 01:57:23,779 INFO: Kucoin announcements enabled, look for new Kucoin coins...
uppers=None

**Comment by alkresha** [comment]
Question: How can I extract the same record that you attached?
Regarding buying and selling information and timing....

**Comment by Linus045** [comment]
```
File "main.py", line 255, in sell
    logger.Info(f"Order is initialized but not ready. Continuing. | Status={st}")
```
This needs to be changed to logger.info(...)

**Comment by Linus045** [comment]
What record are you referring to exactly?
