### ISSUE TITLE
Error from live CHESS detection

### ISSUE THREAD

**Issue by nicoehrenbock** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#25]
I got this error when CHESS was listed. It placed the buy order but then failed:

I had print(order) so heres its output and the error

````
New annoucement detected: CHESS
'Order' object does not support item assignment
{'CHESS': {'account': 'spot',
 'amount': '1.56384392',
 'auto_borrow': None,
 'auto_repay': None,
 'create_time': '1634871636',
 'create_time_ms': 1634871636858,
 'currency_pair': 'CHESS_USDT',
 'fee': '0',
 'fee_currency': 'CHESS',
 'fill_price': '0',
 'filled_total': '0',
 'gt_discount': False,
 'gt_fee': '0',
 'iceberg': '0',
 'id': '231244324',
 'left': '1.32112213',
 'point_fee': '0',
 'price': '6.3945',
 'rebated_fee': '0',
 'rebated_fee_currency': 'USDT',
 'side': 'buy',
 'status': 'open',
 'text': 'apiv4',
 'time_in_force': 'gtc',
 'type': 'limit',
 'update_time': '1634871636',
 'update_time_ms': 1634871636858}}

Traceback (most recent call last):
  File "main.py", line 195, in <module>
    main()
  File "main.py", line 67, in main
    stored_price = float(order[coin]['price'])
TypeError: 'Order' object is not subscriptable
````

**Comment by Linus045** [comment]
I will close this issue, if this is still a problem, feel free to re-open it again.
