### ISSUE TITLE
API exception when a new announcement is detected but the coin is not listed on on gate.io

### ISSUE THREAD

**Issue by davidebonavita** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#4]
It seems that this exception is not handled. Shouldn't it try in a few minutes/hours again if the coin is not listed?

```Checking for coin announcements every 1 minute (in a separate thread)
New annoucement detected: LAZIO
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gate_api/api_client.py", line 190, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/dist-packages/gate_api/api_client.py", line 447, in request
    return self.rest_client.GET(
  File "/usr/local/lib/python3.8/dist-packages/gate_api/rest.py", line 237, in GET
    return self.request(
  File "/usr/local/lib/python3.8/dist-packages/gate_api/rest.py", line 232, in request
    raise ApiException(http_resp=r)
gate_api.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 19 Oct 2021 09:28:30 GMT', 'Content-Type': 'application/json', 'Content-Length': '63', 'Connection': 'keep-alive', 'Server': 'openresty', 'X-Request-Id': '[66c99e50-81227577]'})
HTTP response body: {"label":"INVALID_CURRENCY","message":"Invalid currency LAZIO"}```

**Comment by raulnavarro82** [comment]
I think it would be better to add 'Launchpad' to exclusions, better than 'LAZIO' because it will happen in any Launchpad coin announcement. But it would be much better to fix the error, of course.
