### ISSUE TITLE
KeyError: 'LOGGING' after recent git pull

### ISSUE THREAD

**Issue by kurazli** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#64]
Hi

After having the bot run for about a month or two I decided to do a git pull two days ago.
Since then I'm not able to start it anymore, it gives me the following lines:

`user@computer:~/gateio-crypto-trading-bot-binance-announcements-new-coins$ python3.9 main.py 
Traceback (most recent call last):
  File "/home/user/gateio-crypto-trading-bot-binance-announcements-new-coins/main.py", line 1, in <module>
    from trade_client import *
  File "/home/user/gateio-crypto-trading-bot-binance-announcements-new-coins/trade_client.py", line 1, in <module>
    from logger import logger
  File "/home/user/gateio-crypto-trading-bot-binance-announcements-new-coins/logger.py", line 15, in <module>
    log_level = config['LOGGING']['LOG_LEVEL']
KeyError: 'LOGGING'
`

I already tried to recheck for requirements, but everything seems to be in order.
I also deleted the folder and cloned the code again, but the same error appears.
Is there anything I'm missing?
Any help/pointer appreciated

**Comment by davidebonavita** [comment]
You need to use the new config template

**Comment by kurazli** [comment]
Thank you for the hint, that did the trick!
